version: '3'

networks:
  rustdesk-net:
    driver: bridge    

services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r ${HBBR_HOSTNAME}:21117 -k _
    volumes:
      - ./hbbs:/root
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr -k _
    volumes:
      - ./hbbr:/root
    networks:
      - rustdesk-net
    restart: unless-stopped

  web:
    ports:
      - 8000:8000
    image: codeskyblue/gohttpserver
    command: '--auth-type http --auth-http ${WEB_USERNAME}:${WEB_PASSWORD} --plistproxy="" --google-tracker-id=""'
    volumes:
      - ./webdl:/app/public
    networks:
      - rustdesk-net
    restart: unless-stopped

